# Generated by Django 5.0.14 on 2026-01-26 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosPersonales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("idperfil", models.CharField(max_length=50, unique=True)),
                ("descripcionperfil", models.CharField(max_length=255)),
                (
                    "varyingpic",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("esfotoperfil", models.BooleanField(default=False)),
                ("apellidos", models.CharField(max_length=100)),
                ("nombres", models.CharField(max_length=100)),
                ("nacionalidad", models.CharField(max_length=50)),
                ("lugardenacimiento", models.CharField(max_length=100)),
                ("fechanacimiento", models.DateField()),
                ("numerocedula", models.CharField(max_length=20)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("estadocivil", models.CharField(max_length=20)),
                (
                    "telefonoconvencional",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("telefonocelular", models.CharField(max_length=15)),
                ("direccionhabitual", models.TextField()),
                ("funcionescompetencias", models.TextField()),
                ("activoweb", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfiles_asociados",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CursosRealizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("idcursorealizado", models.CharField(max_length=50, unique=True)),
                ("nombrecurso", models.CharField(max_length=100)),
                ("fechainicio", models.DateField()),
                ("fechafin", models.DateField()),
                (
                    "totalhoras",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("descripcioncurso", models.TextField()),
                ("entidadpatrocinadora", models.CharField(max_length=100)),
                ("nombrereconocimientoasignado", models.CharField(max_length=100)),
                ("telefonocontactoasignado", models.CharField(max_length=15)),
                ("emailempresapatrocinadora", models.EmailField(max_length=254)),
                (
                    "notacertificado",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "rutacertificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_realizados",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Educacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("ideducacion", models.CharField(max_length=50, unique=True)),
                ("titulo", models.CharField(max_length=100)),
                ("institucion", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("en_curso", models.BooleanField(default=False)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "area_conocimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nivel_titulo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "subarea_conocimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rutatitulo",
                    models.FileField(blank=True, null=True, upload_to="titulos/"),
                ),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educacion",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienciaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("idexperiencialaboral", models.CharField(max_length=50, unique=True)),
                ("cargodesempenado", models.CharField(max_length=100)),
                ("nombreempresa", models.CharField(max_length=100)),
                ("lugarempresa", models.CharField(max_length=100)),
                (
                    "telefonocelularempresarial",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "telefonoconvencionalempresarial",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "nombrecontactoprincipalempresarial",
                    models.CharField(max_length=100),
                ),
                ("telefonocontactoempresarial", models.CharField(max_length=15)),
                ("fechainiciocontrato", models.DateField()),
                ("fechafincontrato", models.DateField(blank=True, null=True)),
                ("descripcionfunciones", models.TextField()),
                (
                    "sueldocertificado",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias_laborales",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductosAcademicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("idproductoacademico", models.CharField(max_length=50, unique=True)),
                ("nombrerecurso", models.CharField(max_length=150)),
                ("clasificador", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_academicos",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductosLaborales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("idproductolaboral", models.CharField(max_length=50, unique=True)),
                ("nombreproducto", models.CharField(max_length=150)),
                ("fechaproducto", models.DateField()),
                ("lugarproducto", models.TextField()),
                ("estadoproducto", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                (
                    "valordelibro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_laborales",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reconocimientos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("general", "General"), ("laboral", "Laboral")],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("idreconocimiento", models.CharField(max_length=50, unique=True)),
                ("tiporeconocimiento", models.CharField(max_length=50)),
                ("fechareconocimiento", models.DateField()),
                ("descripcionreconocimiento", models.TextField()),
                ("entidadpatrocinadora", models.CharField(max_length=100)),
                ("nombrecontactoasignado", models.CharField(max_length=100)),
                ("telefonocontactoasignado", models.CharField(max_length=15)),
                (
                    "emailcontacto",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "notacertificado",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "rutareconocimiento",
                    models.FileField(
                        blank=True, null=True, upload_to="reconocimientos/"
                    ),
                ),
                (
                    "idperfilcomparteasociativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconocimientos",
                        to="cv.datospersonales",
                    ),
                ),
            ],
        ),
    ]
