# Generated by Django 5.0.14 on 2026-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoGaraje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos_garaje/"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("bueno", "Bueno"), ("regular", "Regular")],
                        default="bueno",
                        max_length=10,
                    ),
                ),
                (
                    "link_contacto",
                    models.URLField(help_text="URL para contactar al vendedor"),
                ),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Producto de Garaje",
                "verbose_name_plural": "Productos de Garaje",
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.AddField(
            model_name="datospersonales",
            name="email_contacto",
            field=models.EmailField(
                blank=True,
                help_text="Email que se mostrará en la sección de contacto",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datospersonales",
            name="ocupacion",
            field=models.CharField(
                default="Profesión",
                help_text="Ocupación o profesión que aparecerá debajo del nombre",
                max_length=100,
            ),
        ),
    ]
