# Generated by Django 5.0.14 on 2026-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_productogaraje_datospersonales_email_contacto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursosrealizado",
            name="en_curso",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el curso está actualmente en progreso",
            ),
        ),
        migrations.AddField(
            model_name="experiencialaboral",
            name="trabajo_actual",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si es el trabajo actual (hasta la actualidad)",
            ),
        ),
        migrations.AddField(
            model_name="productoslaborales",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen opcional del producto laboral",
                null=True,
                upload_to="productos_laborales/",
            ),
        ),
        migrations.AddField(
            model_name="productoslaborales",
            name="link_proyecto",
            field=models.URLField(
                blank=True,
                help_text="Enlace opcional al proyecto o demostración",
                null=True,
            ),
        ),
    ]
